server:
  port: 1810



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: restaurant-consumer-staff
