server:
  port: 80

spring:
  application:
    name: restaurant-zuul-gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id:
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept
  prefix: /axiuj
  ignored-services: "*"
  routes:
    store-route:
      serviceId: restaurant-consumer-store
      path: /store/**
    staff-route:
      serviceId: restaurant-consumer-staff
      path: /staff/**
    menus-route:
      serviceId: restaurant-consumer-menus
      path: /menus/**
    order-route:
      serviceId: restaurant-consumer-orderitem
      path: /order/**
    chart-route:
      serviceId: restaurant-consumer-chart
      path: /chart/**


