server:
  port: 8031

spring:
  application:
    name: restaurant-procider-category
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.axiuj.springcloud.model.entity

mapper:
  mappers: com.axiuj.springcloud.providercategory.dao
logging:
  level:
    com.axiuj.springcloud.providercategory.dao: debug