server:
  port: 8001

spring:
  application:
    name: restaurant-procider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.axiuj.springcloud.restaurant_api  # 注意：对应实体类的路径

mapper:
  mappers: com.axiuj.springcloud.restaurant_provider_client.dao